export const
    API_CALL_IDENTIFY_PHOTO_REQUEST = "API_CALL_IDENTIFY_PHOTO_REQUEST",
    API_CALL_IDENTIFY_PHOTO_SUCCESS = "API_CALL_IDENTIFY_PHOTO_SUCCESS",
    API_CALL_IDENTIFY_PHOTO_FAILURE = "API_CALL_IDENTIFY_PHOTO_FAILURE",
    API_CALL_PHOTO_SUCCESS = 'API_CALL_PHOTO_SUCCESS'
;
